function [FY_out,MZ_out] = ymSolve(veh, delta, beta, Vx)
% calculate vertical force (axle load + defined aerodynamic force)
fz_front = ((veh.l - veh.a)/veh.l) * (9.8*veh.m);% + 0.7*Vx^2;
fz_rear = (veh.a/veh.l)            * (9.8*veh.m);% + 1.1*Vx^2;

% solve for Fy
syms FY;

alp_front = (delta - veh.a * (FY/veh.m/Vx/Vx)  - beta );
alp_rear = -(beta - (veh.l - veh.a)*(FY/veh.m/Vx/Vx));

FY_front = magicBCDE(veh.front.mu,...
                veh.front.c1,...
                veh.front.c2,...
                veh.front.C,...
                veh.front.E,...
                alp_front,...
                fz_front);
            
FY_rear = magicBCDE(veh.rear.mu,...
                veh.rear.c1,...
                veh.rear.c2,...
                veh.rear.C,...
                veh.rear.E,...
                alp_rear,...
                fz_rear);

f = FY_front + FY_rear - FY;
FY_out = vpasolve(f,FY,1200);


% organize output according to Fy output
alp_front_out = (delta - veh.a * (FY_out/veh.m/Vx/Vx)  - beta );
alp_rear_out = -(beta - (veh.l - veh.a) * (FY_out/veh.m/Vx/Vx));

FY_front_out = magicBCDE(veh.front.mu,...
                veh.front.c1,...
                veh.front.c2,...
                veh.front.C,...
                veh.front.E,...
                alp_front_out,...
                fz_front);
            
FY_rear_out = magicBCDE(veh.rear.mu,...
                veh.rear.c1,...
                veh.rear.c2,...
                veh.rear.C,...
                veh.rear.E,...
                alp_rear_out,...
                fz_rear);
            
MZ_out =  veh.a * FY_front_out - ...
    (veh.l - veh.a) * FY_rear_out;
end